import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#330f1f",
        "surface-container": "#f2ecee",
        "on-primary-fixed-variant": "#65394b",
        "secondary-fixed-dim": "#d7c1c8",
        error: "#ba1a1a",
        "surface-bright": "#fef8fa",
        "outline-variant": "#d4c2c6",
        secondary: "#6b5a60",
        "tertiary-fixed-dim": "#e9c400",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#25181e",
        "on-tertiary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        outline: "#827377",
        "on-surface-variant": "#504447",
        "primary-container": "#f8bbd0",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffd9e4",
        "surface-dim": "#ded9db",
        "on-background": "#1d1b1d",
        "on-tertiary-container": "#665500",
        "on-surface": "#1d1b1d",
        "surface-tint": "#805062",
        "primary-fixed-dim": "#f2b6cb",
        primary: "#805062",
        tertiary: "#705d00",
        "on-primary-container": "#76485a",
        "surface-container-high": "#ece7e9",
        "surface-container-highest": "#e7e1e3",
        "on-primary": "#ffffff",
        "secondary-fixed": "#f4dce4",
        "on-secondary-container": "#716066",
        "on-tertiary-fixed-variant": "#544600",
        "tertiary-fixed": "#ffe16d",
        "surface-variant": "#e7e1e3",
        surface: "#fef8fa",
        "surface-container-low": "#f8f2f4",
        "inverse-primary": "#f2b6cb",
        background: "#fef8fa",
        "inverse-surface": "#323031",
        "secondary-container": "#f4dce4",
        "on-secondary": "#ffffff",
        "tertiary-container": "#efc900",
        "on-secondary-fixed-variant": "#524249",
        "inverse-on-surface": "#f5eff1",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(128, 80, 98, 0.06)",
        glow: "0 0 12px rgba(239, 201, 0, 0.3)",
      },
    },
  },
  plugins: [],
};

export default config;
